export type LocationKeyType =
    | 'campbell-ca'
    | 'cupertino-ca'
    | 'east-palo-alto-ca'
    | 'los-gatos-ca'
    | 'menlo-park-ca'
    | 'milpitas-ca'
    | 'morgan-hill-ca'
    | 'mountain-view-ca'
    | 'palo-alto-ca'
    | 'redwood-city-ca'
    | 'san-jose-downtown-ca'
    | 'san-jose-east-ca'
    | 'san-jose-north-ca'
    | 'san-jose-south-ca'
    | 'san-sose-west-ca'
    | 'santa-clara-ca'
    | 'saratoga-ca'
    | 'sunnyvale-ca'
    | 'willow-glenn-ca'
    | 'san-mateo-ca'
    | 'san-francisco-ca';

export type LocationType =
    | 'Campbell, CA'
    | 'Cupertino, CA'
    | 'East Palo Alto, CA'
    | 'Los Gatos, CA'
    | 'Menlo Park, CA'
    | 'Milpitas, CA'
    | 'Morgan Hill, CA'
    | 'Mountain View, CA'
    | 'Palo Alto, CA'
    | 'Redwood City, CA'
    | 'San Jose Downtown, CA'
    | 'San Jose East, CA'
    | 'San Jose North, CA'
    | 'San Jose South, CA'
    | 'San Jose West, CA'
    | 'Santa Clara, CA'
    | 'Saratoga, CA'
    | 'Sunnyvale, CA'
    | 'Willow Glenn, CA'
    | 'San Mateo, CA'
    | 'San Francisco, CA';
