export type RaceType =
    | 'African American'
    | 'Alaska Native'
    | 'American Indian'
    | 'Asian Indian'
    | 'Black'
    | 'Chinese'
    | 'Filipino'
    | 'Guamanian'
    | 'Japanese'
    | 'Korean'
    | 'Native Hawaiian'
    | 'Pacific Islander'
    | 'Samoan'
    | 'Vietnamese'
    | 'White';
