import EventInterface from '@interfaces/events';

const events: { [key: string]: EventInterface } = {
    'event-1': {
        organization: 'Grace Baptist Church',
        isReligious: true,
        website: 'https://www.graceinsanjose.org',
        tags: ['shower', 'food', 'essentials'],
        venue: 'Grace Baptist Church',
        location: 'san-jose-ca',
        street: 'North Second Street',
        zipcode: 95112,
        start: {
            hour: 10,
            minute: 0,
            period: 'am',
        },
        end: {
            hour: 2,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['tue', 'wed', 'thu'],
    },
    'event-2': {
        organization: 'Food Not Bombs',
        isReligious: false,
        website: 'http://foodnotbombs.net',
        tags: ['food', 'essentials'],
        venue: 'Saint James Park',
        location: 'san-jose-ca',
        street: 'North 2nd Street & East Saint James Street',
        zipcode: 95112,
        start: {
            hour: 2,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 4,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['sun'],
    },
    'event-3': {
        organization: 'Front Door Communities',
        isReligious: false,
        website: 'https://www.fdcsj.org',
        tags: ['food', 'essentials'],
        venue: "Saint Paul's United Methodist Church",
        location: 'san-jose-ca',
        street: '405 South 10th Street',
        zipcode: 95112,
        start: {
            hour: 9,
            minute: 30,
            period: 'am',
        },
        end: {
            hour: 11,
            minute: 0,
            period: 'am',
        },
        frequency: 'weekly',
        day: ['mon', 'tue', 'thu'],
    },
    'event-4': {
        organization: 'Front Door Communities',
        isReligious: false,
        website: 'https://www.fdcsj.org',
        tags: ['food', 'essentials'],
        venue: "Saint Paul's United Methodist Church",
        location: 'san-jose-ca',
        street: '405 South 10th Street',
        zipcode: 95112,
        start: {
            hour: 11,
            minute: 0,
            period: 'am',
        },
        end: {
            hour: 1,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['wed', 'fri'],
    },
    'event-5': {
        organization: 'Dignity On Wheels',
        isReligious: false,
        website: 'http://dignityonwheels.org',
        tags: ['shower'],
        venue: "Saint Paul's United Methodist Church",
        location: 'san-jose-ca',
        street: '405 South 10th Street',
        zipcode: 95112,
        start: {
            hour: 1,
            minute: 0,
            period: 'am',
        },
        end: {
            hour: 5,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['fri'],
    },
    'event-6': {
        organization: 'Recovery Café',
        isReligious: false,
        website: 'https://recoverycafesj.org/',
        tags: ['recovery', 'food'],
        venue: 'Recovery Café',
        location: 'san-jose-ca',
        street: '80 South 5th Street',
        zipcode: 95112,
        start: {
            hour: 10,
            minute: 0,
            period: 'am',
        },
        end: {
            hour: 11,
            minute: 30,
            period: 'am',
        },
        frequency: 'weekly',
        day: ['mon'],
    },
    'event-8': {
        organization: "Martha's Kitchen",
        isReligious: true,
        website: 'https://www.marthas-kitchen.org/',
        tags: ['food'],
        venue: "Martha's Kitchen",
        location: 'san-jose-ca',
        street: '311 Willow Street',
        zipcode: 95110,
        start: {
            hour: 8,
            minute: 30,
            period: 'am',
        },
        end: {
            hour: 9,
            minute: 30,
            period: 'am',
        },
        frequency: 'weekly',
        day: ['thu'],
    },
    'event-9': {
        organization: "Martha's Kitchen",
        isReligious: false,
        website: 'https://www.marthas-kitchen.org/',
        tags: ['food'],
        venue: "Martha's Kitchen",
        location: 'san-jose-ca',
        street: '311 Willow Street',
        zipcode: 95110,
        start: {
            hour: 12,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 1,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['mon', 'fri'],
    },
    'event-10': {
        organization: "Martha's Kitchen",
        isReligious: false,
        website: 'https://www.marthas-kitchen.org/',
        tags: ['food'],
        venue: "Martha's Kitchen",
        location: 'san-jose-ca',
        street: '311 Willow Street',
        zipcode: 95110,
        start: {
            hour: 4,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 5,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['tue', 'wed'],
    },
    'event-11': {
        organization: "Martha's Kitchen",
        isReligious: false,
        website: 'https://www.marthas-kitchen.org/',
        tags: ['groceries'],
        venue: "Martha's Kitchen",
        location: 'san-jose-ca',
        street: '311 Willow Street',
        zipcode: 95110,
        start: {
            hour: 5,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 6,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['tue'],
    },
    'event-12': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['groceries', 'food'],
        venue: 'Our Lady Of Refuge Church',
        location: 'san-jose-ca',
        street: '2165 Lucretia Avenue',
        zipcode: 95122,
        start: {
            hour: 5,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 7,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['tue'],
    },
    'event-13': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['groceries'],
        venue: 'Saint John Vianney Parish',
        location: 'san-jose-ca',
        street: '4600 Hyland Avenue',
        zipcode: 95127,
        start: {
            hour: 2,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 4,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['wed'],
    },
    'event-14': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['groceries'],
        venue: 'Saint Lucy Parish',
        location: 'campbell-ca',
        street: '2350 South Winchester Boulevard',
        zipcode: 95008,
        start: {
            hour: 10,
            minute: 0,
            period: 'am',
        },
        end: {
            hour: 12,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['fri'],
    },
    'event-15': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['groceries'],
        venue: 'Santa Teresa Parish',
        location: 'san-jose-ca',
        street: '794 Calero Avenue',
        zipcode: 95123,
        start: {
            hour: 9,
            minute: 0,
            period: 'am',
        },
        end: {
            hour: 11,
            minute: 0,
            period: 'am',
        },
        frequency: 'weekly',
        day: ['sat'],
    },
    'event-16': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['food'],
        venue: 'Dahl Family Resource Center',
        location: 'san-jose-ca',
        street: '3200 Water Street',
        zipcode: 95111,
        start: {
            hour: 2,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 3,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['tue'],
    },
    'event-17': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['food'],
        venue: 'Shirakawa Family Resource Center',
        location: 'san-jose-ca',
        street: '665 Wool Creek Drive',
        zipcode: 95112,
        start: {
            hour: 2,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 3,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['wed'],
    },
    'event-18': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['food'],
        venue: 'Seven Trees Family Resource Center',
        location: 'san-jose-ca',
        street: '3975 Mira Loma Way',
        zipcode: 95111,
        start: {
            hour: 2,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 3,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['wed'],
    },
    'event-19': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['food'],
        venue: 'Educare Family Resource Center',
        location: 'san-jose-ca',
        street: '1399 Santee Drive',
        zipcode: 95122,
        start: {
            hour: 3,
            minute: 30,
            period: 'pm',
        },
        end: {
            hour: 4,
            minute: 30,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['wed'],
    },
    'event-20': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['groceries', 'food'],
        venue: "Saint Leo's Parish",
        location: 'san-jose-ca',
        street: '88 Race Street',
        zipcode: 95126,
        start: {
            hour: 5,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 6,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['thu'],
    },
    'event-21': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['groceries', 'food'],
        venue: 'Christ The King Parish',
        location: 'san-jose-ca',
        street: '5284 Monterey Road',
        zipcode: 95111,
        start: {
            hour: 4,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 6,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['fri'],
    },
    'event-22': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['food'],
        venue: 'John XXIII Multi-Service Center',
        location: 'san-jose-ca',
        street: '195 East San Fernando Street',
        zipcode: 95112,
        start: {
            hour: 9,
            minute: 45,
            period: 'am',
        },
        end: {
            hour: 12,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['mon', 'tue', 'wed', 'thu', 'fri'],
    },
    'event-23': {
        organization: 'Catholic Charities of Santa Clara County',
        isReligious: true,
        website: 'https://www.ccscc.org',
        tags: ['food'],
        venue: 'John XXIII Multi-Service Center',
        location: 'san-jose-ca',
        street: '195 East San Fernando Street',
        zipcode: 95112,
        start: {
            hour: 1,
            minute: 30,
            period: 'pm',
        },
        end: {
            hour: 5,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['mon', 'tue', 'wed', 'thu', 'fri'],
    },
    'event-24': {
        organization: 'CityTeam',
        isReligious: true,
        website: 'https://cityteam.org/',
        tags: ['food'],
        venue: 'CityTeam',
        location: 'san-jose-ca',
        street: '580 Charles Street',
        zipcode: 95112,
        start: {
            hour: 9,
            minute: 15,
            period: 'am',
        },
        end: {
            hour: 10,
            minute: 15,
            period: 'am',
        },
        frequency: 'weekly',
        day: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    },
    'event-25': {
        organization: 'CityTeam',
        isReligious: true,
        website: 'https://cityteam.org/',
        tags: ['food'],
        venue: 'CityTeam',
        location: 'san-jose-ca',
        street: '580 Charles Street',
        zipcode: 95112,
        start: {
            hour: 5,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 6,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'],
    },
    'event-26': {
        organization: 'CityTeam',
        isReligious: true,
        website: 'https://cityteam.org/',
        tags: ['groceries', 'essentials', 'shower'],
        venue: 'CityTeam',
        location: 'san-jose-ca',
        street: '1297 North 13th Street',
        zipcode: 95112,
        start: {
            hour: 1,
            minute: 0,
            period: 'pm',
        },
        end: {
            hour: 5,
            minute: 0,
            period: 'pm',
        },
        frequency: 'weekly',
        day: ['sun'],
    },
    'event-27': {
        organization: 'Santa Maria Urban Ministry',
        isReligious: true,
        website: 'https://www.santamariasj.org',
        tags: ['groceries'],
        venue: 'Santa Maria Urban Ministry',
        location: 'san-jose-ca',
        street: '778 South Almaden Avenue',
        zipcode: 95110,
        start: {
            hour: 9,
            minute: 0,
            period: 'am',
        },
        end: {
            hour: 11,
            minute: 45,
            period: 'am',
        },
        frequency: 'weekly',
        day: ['mon', 'tue', 'wed', 'thu', 'fri'],
    },
};

export default events;
