name: Check TS
on: [push]

jobs:
  check-ts-deps:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache-dependency-path: package-lock.json
          cache: npm

      - name: Install dependencies
        run: |
          npm install

          if ! test -z "`git diff --stat`"; then
            echo "`npm install` produced changes, exiting"
            git diff --name-only | cat
            exit 1
          fi

  check-ts-format:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache-dependency-path: package-lock.json
          cache: npm

      - name: Install dependencies
        run: |
          npm install

      - name: Check Formatting
        run: |
          npm run pretty --write "./**/*.{ts,tsx,css,json}"

          if ! test -z "`git diff --stat`"; then
            echo "`prettier` produced changes, exiting"
            git diff --name-only | cat
            exit 1
          fi

  check-ts-types:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache-dependency-path: package-lock.json
          cache: npm

      - name: Install dependencies
        run: |
          npm install

      - name: Check Types
        run: npx tsc --noEmit
