name: Check Formatting
on: [push]

jobs:
  check-ts-format:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - id: node-version
        name: Get node version
        run: |
          echo "version=`cat .nvmrc`" >> $GITHUB_OUTPUT

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.node-version.outputs.version }}

      - name: Install Node.js dependencies
        run: |
          npm install

          if ! test -z "`git diff --stat`"; then
            echo "`npm install` produced changes, exiting"
            git diff --name-only | cat
            exit 1
          fi

      - name: Check Formatting
        run: |
          npm run pretty --write "./**/*.{ts,tsx,css,json}"

          if ! test -z "`git diff --stat`"; then
            echo "`prettier` produced changes, exiting"
            git diff --name-only | cat
            exit 1
          fi
